apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-test-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-test-app
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "create", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-test-app
subjects:
- kind: ServiceAccount
  name: deploy-test-app
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-test-app
