apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: test-app
spec:
  params:
  - name: credentialsSecretName
    description: Secret resource name for gcr.io
  - name: credentialsSecretKey
    description: Secret resource key for gcr.io
  resources:
  - name: test-repo
    type: git
  - name: image
    type: image
  tasks:
  - name: gofmt
    taskRef:
      name: gofmt
    params:
    - name: path
      value: /workspace/source-repo/test-app
    resources:
      inputs:
      - name: source-repo
        resource: test-repo
  - name: build-and-push
    taskRef:
      name: kaniko
    params:
    - name: dockerfile
      value: /workspace/source-repo/test-app/Dockerfile
    - name: context
      value: /workspace/source-repo/test-app
    - name: credentialsSecretName
      value: "${params.credentialsSecretName}"
    - name: credentialsSecretKey
      value: "${params.credentialsSecretKey}"
    resources:
      inputs:
      - name: source-repo
        resource: test-repo
      outputs:
      - name: destImage
        resource: image
  - name: jsonnet
    taskRef:
      name: jsonnet
    resources:
      inputs:
      - name: workspace
        resource: test-repo
      - name: image
        resource: image
        from: [build-and-push]
      outputs:
      - name: workspace
        resource: test-repo
    params:
    - name: path
      value: /workspace/test-app/manifest.jsonnet
    - name: outputPath
      value: /workspace/test-app/manifest.json
  - name: deploy
    taskRef:
      name: deploy
    resources:
      inputs:
      - name: workspace
        resource: test-repo
        from: [jsonnet]
    params:
    - name: path
      value: /workspace/test-app/manifest.json
